{% set version = "4.1.1" %}
{% set patchlevel = "p3" %}
{% set name = "singular" %}

package:
  name: {{ name }}
  version: {{ version }}.{{ patchlevel }}

source:
  fn: {{ name }}-{{ version }}{{ patchlevel }}.tar.gz
  url: http://www.mathematik.uni-kl.de/ftp/pub/Math/Singular/SOURCES/{{ version.replace('.', '-') }}/singular-{{ version }}{{ patchlevel }}.tar.gz
  sha256: 551b41060c06878e60119f0283edd09ca7a34d47755fe67d04f5cf9bea4a12e440164c850d5a1575f4bfe95ab884088d03c0449570d40f465611932ffd0bf803

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('singular', max_pin='x.x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - automake
    - pkg-config
  host:
    - gmp
    - mpfr
    - ntl
    - libflint
    - cddlib
    - readline
    - sed
  run:
    - gmp
    - mpfr
    - ntl
    - libflint
    - cddlib
    - readline

test:
  commands:
    - test -f ${PREFIX}/include/singular/Singular/libsingular.h
    - test -f ${PREFIX}/lib/libSingular.a
    - test -f ${PREFIX}/lib/libSingular.dylib     # [osx]
    - test -f ${PREFIX}/lib/libSingular.so        # [linux]

about:
  home: https://www.singular.uni-kl.de/
  license: GPLv2+
  license_file: COPYING
  summary: | 
    Singular is a computer algebra system for polynomial computations, with special emphasis
    on commutative and non-commutative algebra, algebraic geometry, and singularity theory
  dev_url: https://github.com/Singular/Sources

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
