travis:
  secure:
    BINSTAR_TOKEN: Q8655NT3RacWUo+G1xe3uZvTIxBCAnF60A0iIM0peJ8fMw9FbO+r8wwuoFoKTpV4ChgCDpUpotEkuxPI171os42cF+6KmSDYomgDh2+Q9tX/ZnA+QJe/LvC5IX78uCSGjQK5W1yez+czOUaOx6/TXSCJjy9M3fVXXMSIJhb1q9zYbLMiMCLovuD/qUf0I2vPMZtYUDJpv4hZMxDWPrAqBSQMaSE6bN/KUf29w6kcjC+MAx2SjAeFLDEVEQ+DOQ2eEym5wnjBttlYPNZwbsB2SdBPUlXfy/5El0H2G+uurER22VuNUFgWtC328MCD4JMPa2yviG8eSboLWnBgIfOOHqJkGY0ZJfWf+Hmr31BDqUdV3jQVVQMiuAcnV5dLU94kczLY9XVOuYkN+05fHt+PuZELCS7AZKmyvyetVpPFe3X3fmhA/CqEQGXA2MG+v01kEs4Ozx+AhDwNYykrxZl3qqM6jhcS+90NlV0r/HVJLpYY24bYQW+BUzyjp3hEQRePN77KL35+E6maYvGjF9mSm6n/V8FS/uHO6Ux52/cGDOhrl2DMkJCqKNwsL/Xc5APYcIWE4HU+unNcXDltjuPn1Rj9J4Qorq3sg5h1gLFraJUUVH7kFZBNOV+tt3kc75s7maST/D7S25rp55Cr5TbjIDjoCvFdg/5mzaqwZoS3ljU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
