travis:
  secure:
    BINSTAR_TOKEN: HOWGUKmXTI99yb6Sml4wBHgVuV0EW310rTn9nbLOrUmRLU2QEWtBFyJ1YLjnTh7Nfuhk5DototaY+c2ycCid/lcc87H62MIOF7Xf5Fsi7DYdQotjKpcK5MYRtVZHK1FyMBj7MDPFHYH9DmAn+eZHPPpB8suJwYK2PpOiBv7P62dJFuMre+k7uzdX9zxN4s+TV2NCmZ4XC7CnfsfWO/Jcl8DqKKmu0uF3R5jCURqZkfJ0HU6jjJjo2F6z4tNQ+BuFHTptMRfkqne+u2JUy8e5qAemLlrkD1uGL9A2alpT7CsVlzC1thTGpuCniMcLKrv4/GxU2zZH8GYLK0lKPKQkPsojOVkQ7HhCbnMTL5APSXlI5T4oayL8mwxrSoXf0wAlu3nyypgbS9ZwoG5udjbenG5EIHdiO+ffrXUOdZjmiIg6J7QwqqE4lSeSdtnJgDeP967MlUexSVgtJWkWZWz9qOZQ4xeAJjPwOix7clyJeabOfpMIyNVJEST+IBMH/9XG0txtg8Q1hEYvxNXCKHMoZbLr/TaF86LWfNMYNAqoDb3XyXBZcwUbFiOBbbgSrXObkwkn+aOaJIeBryruxGbHH4onLdShBAi2nLsYpnjMGQ7AWulzzDUNben0UBZc7TZJhv/O65uiHSuTjxKA9WY65R9803F6F1Izvsx1MVT3Ydw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
